/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.download.jsonc --env-file=workers/.env.typegen --include-runtime=false --env-interface=DownloadWorkerEnv workers/download-env.d.ts` (hash: 191b2f420fb41d4c1c680eb7fe39e1dd)
interface __BaseEnv_DownloadWorkerEnv {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./download");
	}
	interface Env extends __BaseEnv_DownloadWorkerEnv {}
}
interface DownloadWorkerEnv extends __BaseEnv_DownloadWorkerEnv {}
